apiVersion: v2
appVersion: 0.0.2
description: prometheus exporter for rtl_433
name: rtl-433-exporter
version: 0.0.2
kubeVersion: ">=1.16.0-0"
keywords:
- rtl-433-exporter
- rtl-433
home: https://github.com/markafarrell/rtl_433_prometheus/charts/rtl-433-exporter
sources:
- https://github.com/markafarrell/rtl_433_prometheus
- https://github.com/merbanan/rtl_433
maintainers:
- name: markafarrell
  email: mark.andrew.farrell@gmail.com
dependencies:
- name: common
  repository: https://library-charts.k8s-at-home.com
  version: 4.3.0
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Initial version
